Utility library
nmxhc/StaticAnalysisTPSE pull request #14
Opened 2024-12-15 19:22 UTC by totallynotadolphin

merge

2024-12-16 09:33 UTC, nmxhc requested changes, later dismissed

2024-12-16 09:33 UTC, nmxhc commented on src/test/java/UtilTest.java
> +        Optional<SootClass> realClass = Util.loadClass("Test");
Meinem bisherigen Verständnis nach sind die Inhalte des `demo` Verzeichnisses recht variabel. Dann sollten wir nicht unsere Tests davon abhängig machen, sondern sie in einen anderen Ordner schieben.

2024-12-16 09:33 UTC, nmxhc commented on src/test/java/UtilTest.java
> +        assert(methodNames.size() == 4);
Das braucht einen Kommentar, warum hier eine Methode mehr sein soll, als wir testen.

2024-12-18 11:04 UTC, betterNameStillPending commented
merge

2024-12-18 11:14 UTC, betterNameStillPending approved these changes, later dismissed

2024-12-18 11:16 UTC, merged